# Generated by Django 3.1.5 on 2022-02-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='start_date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='datetime',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='체크시간'),
        ),
    ]
